name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: 'refs/heads/master'

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Build and deploy
        run: |
          mkdir gh-pages
          cp -r dist2/* gh-pages/
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git checkout --orphan gh-pages
          git add --all
          git commit -m "Deploy to GitHub Pages by GitHub Actions"
          git remote add gh-pages-remote https://${{ github.actor }}:${{ secrets.GH_TOKEN }}@github.com/${{ github.repository }}.git
          git push --force gh-pages-remote HEAD:gh-pages